name: artgig
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.8.4
  fluttertoast: ^8.0.8
  entry: ^0.0.8+1
  # firebase_auth: ^4.12.1
  # firebase_core: ^2.21.0
  # firebase_messaging: ^14.6.0
  # google_sign_in: ^6.0.2
  # sign_in_with_apple: ^4.3.0
  # flutter_local_notifications: 9.5.2
  # connectivity_plus: ^3.0.6
  intl:
  # dio: ^4.0.0
  # shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.5.0
  keyboard_actions: ^4.2.0
  extended_image: 8.1.0
  image_picker: ^0.8.5+3
  another_flushbar: ^1.12.30
  webview_flutter: ^3.0.4
  flutter_pin_code_fields: ^2.2.0
  circular_countdown_timer: ^0.2.2
  easy_stepper: ^0.8.4
  permission_handler: ^11.3.0
  mime: ^1.0.5
  device_info_plus: ^9.0.0
  dropdown_button2: ^2.3.2
  timeago: ^3.2.2
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.0
  # flutter_stripe: ^6.0.0
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Jones-Light
      fonts:
        - asset: assets/fonts/Jones-Light.otf
    - family: Jones-Regular
      fonts:
        - asset: assets/fonts/Jones-Book.otf
    - family: Jones-Medium
      fonts:
        - asset: assets/fonts/Jones-Medium.otf
    - family: Jones-Bold
      fonts:
        - asset: assets/fonts/Jones-Bold.otf
    - family: Jones-ExtraBold
      fonts:
        - asset: assets/fonts/Jones-Black.otf
