class ChatThread {
/*
{
  "object_type": "get_messages",
  "data": [
    {
      "first_name": "John",
      "last_name": "Abraham",
      "profile_image": "profile_image/8XmijOgEitCu39eR3ZsofsC3Xz86aeiDA9ZZPJ1m.jpg",
      "id": 2,
      "conversation_id": 2,
      "sender_id": 16,
      "receiver_id": 1,
      "type": "text",
      "message": "hello testing",
      "read_at": null,
      "status": null,
      "created_at": "2024-07-10T08:50:04.000Z",
      "updated_at": null
    }
  ]
} 
*/

  String? objectType;
  List<ChatThreadData?>? data;

  ChatThread({
    this.objectType,
    this.data,
  });
  ChatThread.fromJson(Map<String, dynamic> json) {
    objectType = json['object_type']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ChatThreadData>[];
      v.forEach((v) {
        arr0.add(ChatThreadData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['object_type'] = objectType;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChatThreadData {
/*
{
  "first_name": "John",
  "last_name": "Abraham",
  "profile_image": "profile_image/8XmijOgEitCu39eR3ZsofsC3Xz86aeiDA9ZZPJ1m.jpg",
  "id": 2,
  "conversation_id": 2,
  "sender_id": 16,
  "receiver_id": 1,
  "type": "text",
  "message": "hello testing",
  "read_at": null,
  "status": null,
  "created_at": "2024-07-10T08:50:04.000Z",
  "updated_at": null
} 
*/

  String? firstName;
  String? lastName;
  String? profileImage;
  int? id;
  int? conversationId;
  int? senderId;
  int? receiverId;
  String? type;
  String? message;
  String? readAt;
  String? status;
  String? createdAt;
  String? updatedAt;

  ChatThreadData({
    this.firstName,
    this.lastName,
    this.profileImage,
    this.id,
    this.conversationId,
    this.senderId,
    this.receiverId,
    this.type,
    this.message,
    this.readAt,
    this.status,
    this.createdAt,
    this.updatedAt,
  });
  ChatThreadData.fromJson(Map<String, dynamic> json) {
    firstName = json['first_name']?.toString();
    lastName = json['last_name']?.toString();
    profileImage = json['profile_image']?.toString();
    id = json['id']?.toInt();
    conversationId = json['conversation_id']?.toInt();
    senderId = json['sender_id']?.toInt();
    receiverId = json['receiver_id']?.toInt();
    type = json['type']?.toString();
    message = json['message']?.toString();
    readAt = json['read_at']?.toString();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['first_name'] = firstName;
    data['last_name'] = lastName;
    data['profile_image'] = profileImage;
    data['id'] = id;
    data['conversation_id'] = conversationId;
    data['sender_id'] = senderId;
    data['receiver_id'] = receiverId;
    data['type'] = type;
    data['message'] = message;
    data['read_at'] = readAt;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}
